### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by rkpatel33** [yetzt/pdf3json#1]
@yetzt, I'm having trouble understanding the coordinate system employed here, could you shed a little light on it? In particular, I am trying to understand how to transform it to the PDF point coordinate system (72 points per inch starting from the bottom left corner).

Thx.

**Comment by yetzt** [comment]
i dug a bit around in [pdf2json](https://code.google.com/p/pdf2json/) and [xpdf](http://www.foolabs.com/xpdf/). the pdf2json code calls `displayPages()` [from xpdf](https://github.com/yetzt/pdf3json/blob/master/xpdf/PDFDoc.cc) with 108 (`double scale=1.5;` and `static_cast<int>(72*scale)` in [pdf3json.cc](https://github.com/yetzt/pdf3json/blob/master/src/pdf3json.cc)) as horizontal and vertical dpi. so if you want to convert it to 72 dpi, divide everything by 1.5 or change the scale variable in [pdf3json.cc](https://github.com/yetzt/pdf3json/blob/master/src/pdf3json.cc)
